MishMashExamWithAspNetCore/MishMashExamASP.NET/MishMashExamASP.NET/Controllers/CarAdController.cs
    using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Localization;
    using MishMashExamASP.NET.Models.CarAd;

    namespace MishMashExamASP.NET.Controllers
{
    public class CarAdController : Controller
    {
        public CarAdController()
        {
            
        }
        public IActionResult Create()
        {
            //TODO: default values
            var model = new CreateInputModel()
            {
                LongDescription = "initial value"
            };
            return this.View(model);
        }
        [HttpPost]
        public IActionResult Create(CreateInputModel inputModel)
        {
            if (!ModelState.IsValid)
            {
                return this.View(inputModel);
            }

            return this.Json(inputModel);
        }
    }
}

MishMashExamWithAspNetCore/MishMashExamASP.NET/MishMashExamASP.NET/Controllers/ChannelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MishMashExamASP.NET.Data.Models;
using MishMashExamASP.NET.Models;
using MishMashExamASP.NET.Services.Channels;

namespace MishMashExamASP.NET.Controllers
{
    public class ChannelsController : Controller
    {
        private readonly IChannelServices channelServices;

        public ChannelsController(IChannelServices channelServices)
        {
            this.channelServices = channelServices;
        }

        [HttpGet]
        public IActionResult Create()
        {
            var inputModel = new CreateChannelInputModel()
            {
                ChannelTypes = new string[] {"Game", "Motivation", "Lessons", "Radio", "Other"}
            };

            return this.View(inputModel);
        }

        [HttpPost]
        public IActionResult CreateChannel(CreateChannelInputModel inputModel)
        {
            this.channelServices.CreateChannel(inputModel);
            return this.RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult FollowChannel(string channelId)
        {
            this.channelServices.FollowChannel(this.User, channelId);
            return this.Json(channelId);
        }

        [HttpPost]
        public IActionResult UnfollowChannel(string channelId)
        {
            this.channelServices.UnfollowChannel(this.User, channelId);
            return this.Json(channelId);
        }

        public IActionResult Details(string id)
        {
            var viewModel = this.channelServices.GetChannelDetailsModel(id);
            return this.View(viewModel);
        }

        public IActionResult MyChannels()
        {
            var model = this.channelServices.GetFollowingChannels(this.User);
            return this.View(model);
        }
    }
}

MishMashExamWithAspNetCore/MishMashExamASP.NET/MishMashExamASP.NET/Views/Shared/_ChannelsListPartial.cshtml
@model ICollection<ChannelBoxViewModel>
<div class="channel-group" id="other-channels">
    @foreach (var channel in Model)
    {
        <div class="channel-box">
            <h5>@channel.Name</h5>
            <hr />
            <h5>@channel.Type Channel</h5>
            <hr />
            <h5>Followers @channel.Followers</h5>
            <hr />
            <div class="channelActions">
                <button class="follow-channel" data-channel-id="@channel.Id">Follow</button>
                <a asp-controller="Channels" asp-action="Details" asp-route-id="@channel.Id">Details</a>
            </div>
        </div>
    }
</div>

MishMashExamWithAspNetCore/MishMashExamASP.NET/MishMashExamASP.NET/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MishMashExamASP.NET</title>


    <link rel="stylesheet" href="~/css/reset-css.css" />
    <environment include="Development,Stage,Production">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <link rel="stylesheet" href="~/css/style.css" />
</head>
<body>  
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-mishmash">
            <a class="navbar-brand nav-link-white" href="/">Mish Mash</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link nav-link-white active" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-link-white active" asp-controller="CarAd" asp-action="Create">Add ad for a car</a>
                    </li>
                    @if (this.User.Identity.IsAuthenticated)
                    { 
                        <li class="nav-item">
                            <a class="nav-link nav-link-white active" asp-controller="Channels" asp-action="MyChannels">My Channels</a>
                        </li>
                        if (this.User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link nav-link-white active" asp-controller="Channels" asp-action="Create">Create Channel</a>
                            </li>
                        }
                        <li class="nav-item">
                            <form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new {area = ""})" method="post" id="logoutForm">
                                <button type="submit" class="nav-link nav-link-white active">Logout</button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link nav-link-white active" asp-area="Identity" asp-page="/Account/Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav-link-white active" asp-area="Identity" asp-page="/Account/Register">Register</a>
                        </li>


                    }

                    @RenderSection("MenuItems", false);

                </ul>
            </div>
        </nav>
    </header>

    @RenderBody()

    <footer>
        <div class="container-fluid bg-mishmash">
            <div class="text-white p-2 text-center">
                &copy; CopyRight Sanity Web Design Studios 2018. All rights reserved.
            </div>
        </div>
    </footer>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="/js/site.js"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>